2Trimestre/Unit-11/projects/Biblioteca/src/Entity/Prestamos.php
<?php

namespace App\Entity;

use App\Repository\PrestamosRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PrestamosRepository::class)]
class Prestamos
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\ManyToOne(targetEntity: Libros::class)]
    #[ORM\JoinColumn(nullable: false)]
    private $libro_id;

    #[ORM\ManyToOne(targetEntity: Usuarios::class, inversedBy: 'prestamos')]
    #[ORM\JoinColumn(nullable: false)]
    private $usuario_id;

    #[ORM\Column(type: 'datetime')]
    private $completionDate;

    #[ORM\Column(type: 'datetime')]
    private $maxDelayDate;

    #[ORM\Column(type: 'datetime')]
    private $returnDate;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibroId(): ?Libros
    {
        return $this->libro_id;
    }

    public function setLibroId(?Libros $libro_id): self
    {
        $this->libro_id = $libro_id;

        return $this;
    }

    public function getUsuarioId(): ?Usuarios
    {
        return $this->usuario_id;
    }

    public function setUsuarioId(?Usuarios $usuario_id): self
    {
        $this->usuario_id = $usuario_id;

        return $this;
    }

    public function getCompletionDate(): ?\DateTimeInterface
    {
        return $this->completionDate;
    }

    public function setCompletionDate(\DateTimeInterface $completionDate): self
    {
        $this->completionDate = $completionDate;

        return $this;
    }

    public function getMaxDelayDate(): ?\DateTimeInterface
    {
        return $this->maxDelayDate;
    }

    public function setMaxDelayDate(\DateTimeInterface $maxDelayDate): self
    {
        $this->maxDelayDate = $maxDelayDate;

        return $this;
    }

    public function getReturnDate(): ?\DateTimeInterface
    {
        return $this->returnDate;
    }

    public function setReturnDate(\DateTimeInterface $returnDate): self
    {
        $this->returnDate = $returnDate;

        return $this;
    }
}

2Trimestre/Unit-11/projects/Biblioteca/templates/models/book.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <p>Titule: <span>{{ book.titulo }}</span></p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <p>Editorial: <span>{{ book.editorial }}</span></p>
        </div>
        <div class="col-md-6">
            <p>Genero: <span>{{ book.genero }}</span></p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <p>Autor: <span>{{ book.autor }}</span></p>
        </div>
        <div class="col-md-4">
            <p>Pais: <span>{{ book.pais }}</span></p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <p>Num paginas: <span>{{ book.nPaginas }}</span></p>
        </div>
        <div class="col-md-6">
            <p>Precio: <span>{{ book.precio }}</span></p>
        </div>
    </div>
</div>
{% endblock %}

2Trimestre/Unit-11/projects/Biblioteca/templates/models/prestamo.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <p>Libro prestado: <span>{% book.titulo %}</span></p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <p>Usuario al que se le ha prestado: <span>{% user.nombre %}{% user.apellidos %}</span></p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <p>Fecha de devoluci&oacute;n: <span>{% prestamo.returnDate %}</span></p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            <p>Fecha en la que se presto el libro: <span>{% prestamo.completionDate %}</span></p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            <p>Fecha maxima de devoluci&oacute;n: <span>{% prestamo.maxDelayDate %}</span></p>
        </div>
    </div>
</div>
{% endblock %}

2Trimestre/Unit-11/projects/Biblioteca/templates/models/user.html.twig
{% extends 'main/users.html.twig' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <p><strong>Nombre completo:</strong> <span>{{ user.nombre }} {{ user.apellidos }}</span></p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8">
            <p><strong>DNI:</strong> <span>{{ user.dni }}</span></p>
        </div>
        <div class="col-md-4">
            <p><strong>Fecha de nacimiento:</strong> <span>{{ user.birthday|date('Y-m-d') }}</span></p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <p><strong>Direcci&oacute;n:</strong> <span>{{ user.provincia }}, {{ user.poblacion }}, {{ user.domicilio }}</span></p>
        </div>
    </div>
    <div class="row">
        {% for prestamo in user.prestamos %}
            <div class="col-md-6">
                <div class="product-item">
                    <div class="down-content">
                        <a href="/book/{{ prestamo.libroId.id }}"><h4>{{prestamo.libroId.titulo}}</h4></a>
                        <p>Fecha de devoluci&oacute;n: <strong>{{ prestamo.returnDate|date('Y-m-d') }}</strong></p>
                        <p>Fecha en la que se presto el libro: <strong>{{ prestamo.completionDate|date('Y-m-d') }}</strong></p>
                        <p>Fecha maxima de devoluci&oacute;n: <strong>{{ prestamo.maxDelayDate|date('Y-m-d') }}</strong></p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}